-- MySQL Script generated by MySQL Workbench
-- Wed Dec  8 23:25:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `schema` ;

-- -----------------------------------------------------
-- Schema schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schema` DEFAULT CHARACTER SET utf8 ;
USE `schema` ;

-- -----------------------------------------------------
-- Table `schema`.`stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schema`.`stations` ;

CREATE TABLE IF NOT EXISTS `schema`.`stations` (
  `stationid` INT NOT NULL,
  `location` VARCHAR(50) NOT NULL COMMENT 'This table represents the different stations adn their attributes',
  `geo_point_2d` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`stationid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schema`.`readings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schema`.`readings` ;

CREATE TABLE IF NOT EXISTS `schema`.`readings` (
  `readingid` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `nox` FLOAT NULL,
  `no2` FLOAT NULL,
  `no` FLOAT NULL,
  `pm 10` FLOAT NOT NULL,
  `nvpm 10` FLOAT NULL,
  `vpm 10` FLOAT NULL,
  `mvpm 2.5` FLOAT NULL,
  `pm 2.5` FLOAT NULL,
  `vpm 2.5` FLOAT NULL,
  `co` FLOAT NULL,
  `o3` FLOAT NULL,
  `so2` FLOAT NULL,
  `temperature` REAL NULL,
  `rh` INT NULL,
  `airpressure` INT NULL,
  `datestart` DATETIME NULL,
  `dateend` DATETIME NULL,
  `current` TEXT(5) NULL,
  `instrumenttype` VARCHAR(35) NULL,
  `stationid-fk` INT NOT NULL,
  PRIMARY KEY (`readingid`, `pm 10`),
  INDEX `stationid_idx` (`stationid-fk` ASC),
  CONSTRAINT `stationid`
    FOREIGN KEY (`stationid-fk`)
    REFERENCES `schema`.`stations` (`stationid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schema`.`Schema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schema`.`Schema` ;

CREATE TABLE IF NOT EXISTS `schema`.`Schema` (
  `measure` VARCHAR(32) NOT NULL,
  `description` VARCHAR(65) NOT NULL,
  `unit` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`measure`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
